apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-app
labels:
  - includeSelectors: true
    pairs:
      app: example-app
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
