---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  # Custom server block for internal domains. All internal domains should
  # resolve to the cluster proxy.
  internal.server: |
    internal.cloud2.payne.io {
      errors
      cache 30
      reload
      template IN A {
        match (.*)\.internal\.cloud2\.payne\.io\.
        answer "{{ .Name }} 60 IN A 192.168.8.20"
      }
      template IN AAAA {
        match (.*)\.internal\.cloud2\.payne\.io\.
        rcode NXDOMAIN
      }
    }
  # Custom override to set external resolvers.
  external.override: |
    forward . 1.1.1.1 {
      max_concurrent 1000
    }
