apiVersion: v1
kind: Service
metadata:
  name: traefik-crowdsec-bouncer
  namespace: crowdsec
  labels:
    app: traefik-crowdsec-bouncer
    managedBy: kustomize
    partOf: wild-cloud
spec:
  type: ClusterIP
  selector:
    app: traefik-crowdsec-bouncer
    managedBy: kustomize
    partOf: wild-cloud
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
