apiVersion: batch/v1
kind: Job
metadata:
  name: nextcloud-db-init
spec:
  template:
    spec:
      containers:
        - name: db-init
          image: postgres:15
          command: ["/bin/bash", "-c"]
          args:
            - |
              PGPASSWORD=${POSTGRES_ADMIN_PASSWORD} psql -h ${NEXTCLOUD_DB_HOST} -U postgres <<EOF
              CREATE USER ${NEXTCLOUD_DB_USER} WITH ENCRYPTED PASSWORD '${NEXTCLOUD_DB_PASSWORD}';
              CREATE DATABASE ${NEXTCLOUD_DB_NAME} WITH OWNER ${NEXTCLOUD_DB_USER};
              GRANT ALL PRIVILEGES ON DATABASE ${NEXTCLOUD_DB_NAME} TO ${NEXTCLOUD_DB_USER};
              EOF
          env:
            - name: POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_ADMIN_PASSWORD
            - name: NEXTCLOUD_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NEXTCLOUD_DB_HOST
            - name: NEXTCLOUD_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NEXTCLOUD_DB_NAME
            - name: NEXTCLOUD_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NEXTCLOUD_DB_USER
            - name: NEXTCLOUD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: NEXTCLOUD_DB_PASSWORD
      restartPolicy: OnFailure
