wildcloud:
  repository: /home/adam/wildcloud
operator:
  email: adam@adam.tld
cloud:
  domain: cloud.adam.tld
  internalDomain: internal.cloud.adam.tld
  dockerRegistryHost: docker-registry.internal.cloud.adam.tld
  tz: America/Los_Angeles
  router:
    dynamicDns: <dynamic dns addresses> # Some routers provide this.
    ip: 192.168.8.1
  nfs:
    host: box-01
    mediaPath: /data/media
    storageCapacity: 250Gi
  dns:
    ip: 192.168.8.218
    externalResolver: 1.1.1.1
  dhcpRange: 192.168.8.100,192.168.8.239
  dnsmasq:
    interface: enp5s0
    username: adam
cluster:
  nodes:
    talos:
      version: v1.10.3
    schematic:
      customization:
        extraKernelArgs:
          - -talos.halt_if_installed
        systemExtensions:
          officialExtensions:
            - siderolabs/gvisor
            - siderolabs/intel-ucode
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
      schematicId: TBD
    control:
      vip: 192.168.8.30
      node1:
        ip: 192.168.8.31
      node2:
        ip: 192.168.8.32
      node3:
        ip: 192.168.8.33
  name: adam-cluster
  ipaddressPool: 192.168.8.20-192.168.8.29
  loadBalancerIp: 192.168.8.20
  kubernetes:
    config: /home/adam/.kube/config
    context: default
  dashboard:
    adminUsername: admin
  certManager:
    namespace: cert-manager
    cloudflare:
      domain: adam.tld
      ownerId: cloud-adam-cluster
  externalDns:
    ownerId: cloud-adam-cluster
  dockerRegistry:
    storage: 10Gi
