apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
labels:
  - includeSelectors: true
    pairs:
      app: nextcloud
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - cron.yaml
  - deployment.yaml
  - headers.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
configMapGenerator:
  - name: config
    envs:
      - config/config.env
secretGenerator:
  - name: secrets
    envs:
      - config/secrets.env

replacements:
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.DOMAIN
    targets:
      - select:
          kind: Ingress
          name: nextcloud-public
        fieldPaths:
          - metadata.annotations.[external-dns.alpha.kubernetes.io/target]
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.NEXTCLOUD_DOMAIN
    targets:
      - select:
          kind: Ingress
          name: nextcloud-public
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.NEXTCLOUD_NFS_STORAGE
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: nextcloud-pvc-nfs
        fieldPaths:
          - spec.resources.requests.storage
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.NEXTCLOUD_STORAGE
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: nextcloud-pvc
        fieldPaths:
          - spec.resources.requests.storage
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.NEXTCLOUD_IMAGE
    targets:
      - select:
          kind: Deployment
          name: nextcloud
        fieldPaths:
          - spec.template.spec.containers.0.image
      - select:
          kind: CronJob
          name: nextcloud-cron
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.0.image
