---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc-nfs
spec:
  storageClassName: longhorn # Change this to nfs-client if using NFS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
