---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
        component: machine-learning
    spec:
      containers:
        - image: "{{ .config.apps.immich.mlImage }}"
          name: immich-machine-learning
          ports:
            - containerPort: {{ .config.apps.immich.mlPort }}
              protocol: TCP
          env:
            - name: TZ
              value: "{{ .config.apps.immich.timezone }}"
          volumeMounts:
            - mountPath: /cache
              name: immich-cache
              readOnly: false
      volumes:
        - name: immich-cache
          persistentVolumeClaim:
            claimName: immich-cache-pvc
