---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: immich-server
        component: server
    spec:
      containers:
        - image: "{{ .config.apps.immich.serverImage }}"
          name: immich-server
          ports:
            - containerPort: {{ .config.apps.immich.serverPort }}
              protocol: TCP
          env:
            - name: REDIS_HOSTNAME
              value: "{{ .config.apps.immich.redisHostname }}"
            - name: DB_HOSTNAME
              value: "{{ .config.apps.immich.dbHostname }}"
            - name: DB_USERNAME
              value: "{{ .config.apps.immich.dbUsername }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: dbPassword
            - name: TZ
              value: "{{ .config.apps.immich.timezone }}"
            - name: IMMICH_WORKERS_EXCLUDE
              value: microservices
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immich-storage
              readOnly: false
      volumes:
        - name: immich-storage
          persistentVolumeClaim:
            claimName: immich-pvc
