---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .config.apps.immich.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-cache-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .config.apps.immich.cacheStorage }}
