---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
spec:
  ports:
    - port: 3001
      targetPort: 2283
  selector:
    app: immich
    component: server
    managedBy: kustomize
    partOf: wild-cloud
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app: immich-machine-learning
spec:
  ports:
    - port: 3003
  selector:
    app: immich
    component: machine-learning
    managedBy: kustomize
    partOf: wild-cloud
