apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent-volume.yaml
  - storage-class.yaml

replacements:
  - source:
      kind: ConfigMap
      name: nfs-config
      fieldPath: data.NFS_HOST_IP
    targets:
      - select:
          kind: PersistentVolume
          name: nfs-media-pv
        fieldPaths:
          - spec.nfs.server
      - select:
          kind: StorageClass
          name: nfs
        fieldPaths:
          - parameters.server
  - source:
      kind: ConfigMap
      name: nfs-config
      fieldPath: data.NFS_MEDIA_PATH
    targets:
      - select:
          kind: PersistentVolume
          name: nfs-media-pv
        fieldPaths:
          - spec.nfs.path
      - select:
          kind: StorageClass
          name: nfs
        fieldPaths:
          - parameters.path
  - source:
      kind: ConfigMap
      name: nfs-config
      fieldPath: data.NFS_STORAGE_CAPACITY
    targets:
      - select:
          kind: PersistentVolume
          name: nfs-media-pv
        fieldPaths:
          - spec.capacity.storage

configMapGenerator:
  - name: nfs-config
    envs:
      - config/config.env