apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  labels:
    storage: nfs-media
spec:
  capacity:
    storage: REPLACE_ME
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: REPLACE_ME
    path: REPLACE_ME
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - intr
    - timeo=600