apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  labels:
    storage: nfs-media
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: box-01
    path: /data/media
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - intr
    - timeo=600