apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    # LAN DNS. All internal domains should resolve to the proxy.
    internal.cloud.payne.io:53 {
      errors
      cache 30
      reload
      template IN A {
        match (.*)\.internal\.cloud\.payne\.io\.
        answer "{{ .Name }} 60 IN A 192.168.8.240"
      }
    }

    # In-cloud DNS
    .:53 {
      health
      errors
      cache 30
      reload
      loop
      ready
      loadbalance
      kubernetes cluster.local in-addr.arpa ip6.arpa {
          fallthrough in-addr.arpa ip6.arpa
      }
      hosts /etc/coredns/NodeHosts {
          fallthrough
      }
      forward . 1.1.1.1 8.8.8.8 {
        max_concurrent 1000
      }
    }

  NodeHosts: |
    192.168.8.218 box-01
    192.168.8.222 civil

    # 192.168.8.240 dashboard.internal.${DOMAIN}
