apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
labels:
  - includeSelectors: true
    pairs:
      app: postgres
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - pvc.yaml
