apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
labels:
  - includeSelectors: true
    pairs:
      app: postgres
      managedBy: kustomize
      partOf: sovereign-cloud
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - pvc.yaml
configMapGenerator:
  - name: config
    envs:
      - config/config.env
secretGenerator:
  - name: secrets
    envs:
      - config/secrets.env

replacements:
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.POSTGRES_STORAGE
    targets:
      - fieldPaths:
          - spec.resources.requests.storage
        select:
          kind: PersistentVolumeClaim
          name: postgresql-pvc
