apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
labels:
  - includeSelectors: true
    pairs:
      app: postgres
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - config
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - pvc.yaml

replacements:
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.POSTGRES_STORAGE
    targets:
      - fieldPaths:
          - spec.resources.requests.storage
        select:
          kind: PersistentVolumeClaim
          name: postgresql-pvc
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.POSTGRES_IMAGE
    targets:
      - fieldPaths:
          - spec.template.spec.containers.0.image
        select:
          kind: Deployment
          name: postgres-deployment
