namespace: metallb-system
resources:
  - pool.yaml
configMapGenerator:
  - name: metallb-config
    envs:
      - config/config.env
replacements:
  - source:
      kind: ConfigMap
      name: metallb-config
      fieldPath: data.CLUSTER_LOAD_BALANCER_RANGE
    targets:
      - select:
          kind: IPAddressPool
          name: first-pool
        fieldPaths:
          - spec.addresses.0
