---
# Source: ghost/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghost
  namespace: "default"
  labels:
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/managed-by: Sovereign
    app.kubernetes.io/name: ghost
    app.kubernetes.io/version: 5.118.1
type: Opaque
data:
  ghost-password: "NnhXejdkNm9KTw=="
