---
# Source: ghost/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghost
  namespace: "default"
  labels:
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/managed-by: Sovereign
    app.kubernetes.io/name: ghost
    app.kubernetes.io/version: 5.118.1
    app.kubernetes.io/component: ghost
automountServiceAccountToken: false
