apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-admin
labels:
  - includeSelectors: true
    pairs:
      app: example-admin
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
