---
apiVersion: v1
kind: Service
metadata:
  name: example-admin
  namespace: example-admin
  labels:
    app: example-admin
spec:
  selector:
    app: example-admin
  ports:
    - port: 80
      targetPort: 80
      name: http
