name: traefik
description: Cloud-native reverse proxy and ingress controller
version: v3.4
namespace: traefik
category: infrastructure

dependencies:
  - metallb

configReferences:
  - cluster.loadBalancerIp
