apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
labels:
  - includeSelectors: true
    pairs:
      app: redis
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
