---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  ports:
    - port: {{ .config.apps.redis.port }}
      targetPort: {{ .config.apps.redis.port }}
  selector:
    app: redis
