apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: metallb
  namespace: kube-system
spec:
  valuesContent: |-
    apiVersion: v1
    crds:
      enabled: true
    controller:
      configInline: null