apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
  - test-job.yaml
labels:
  - includeSelectors: true
    pairs:
      app: postgres-doctor
      managedBy: kustomize
      partOf: wild-cloud
