---
# Source: ghost/charts/mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghost-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.4.5
    helm.sh/chart: mysql-12.3.4
    app.kubernetes.io/part-of: mysql
type: Opaque
data:
  mysql-root-password: "SnVOdks2T2tDdA=="
  mysql-password: "eGllcFBUZWJabw=="
